name: Jekyll Deploy

on: [push]

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
        with:
          jekyll_build_opts: --incremental
          github_token: ${{ secrets.GITHUB_TOKEN }}
